"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', '0').strip().lower() in ('1', 'true', 'yes', 'on')

_allowed_hosts_raw = os.getenv('ALLOWED_HOSTS', '').strip()
if _allowed_hosts_raw:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()]
else:
    # Безопасный дефолт: локально/внутри docker-сети
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend']


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

ASGI_APPLICATION = 'backend.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('redis', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'autoparts',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'db',
        'PORT': '5432',
        'OPTIONS': {
            'connect_timeout': 30,
            'options': '-c statement_timeout=60000',
        },
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройки для загрузки файлов
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Дополнительные настройки для отладки
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Создаем директории если их нет (с обработкой ошибок)
try:
    os.makedirs(MEDIA_ROOT, exist_ok=True)
    os.makedirs(os.path.join(MEDIA_ROOT, 'uploads'), exist_ok=True)
    os.makedirs(os.path.join(MEDIA_ROOT, 'results'), exist_ok=True)
    os.makedirs(os.path.join(MEDIA_ROOT, 'temp'), exist_ok=True)
    FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'media', 'temp')
    print(f"✅ Директории созданы: {MEDIA_ROOT}")
except PermissionError:
    # Если нет прав, используем временную директорию
    import tempfile
    FILE_UPLOAD_TEMP_DIR = tempfile.gettempdir()
    print(f"⚠️ Используем временную директорию: {FILE_UPLOAD_TEMP_DIR}")
except Exception as e:
    print(f"⚠️ Ошибка создания директорий: {e}")
    import tempfile
    FILE_UPLOAD_TEMP_DIR = tempfile.gettempdir()
    print(f"⚠️ Используем временную директорию: {FILE_UPLOAD_TEMP_DIR}")
except Exception as e:
    print(f"⚠️ Ошибка создания директорий: {e}")
    # Используем временную директорию как fallback
    import tempfile
    FILE_UPLOAD_TEMP_DIR = tempfile.gettempdir()

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    'cleanup-media-results-daily': {
        'task': 'api.tasks.cleanup_old_media_results',
        'schedule': crontab(hour=4, minute=0),
    },
}

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000").split(",") if o.strip()
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_BEAT_SCHEDULE_FILENAME = os.path.join(MEDIA_ROOT, 'temp', 'celerybeat-schedule')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Оптимизация для больших файлов
CELERY_WORKER_CONCURRENCY = 2  # Два воркера для параллельной обработки
CELERY_WORKER_MAX_TASKS_PER_CHILD = 3  # Перезапуск воркера после 3 задач
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Берем только одну задачу за раз
CELERY_TASK_ACKS_LATE = True  # Подтверждаем задачу после выполнения для надежности
CELERY_WORKER_DISABLE_RATE_LIMITS = True  # Отключаем ограничения скорости
CELERY_TASK_TIME_LIMIT = 360000  # Максимальное время выполнения задачи (100 часов) - увеличен для очень больших файлов
CELERY_TASK_SOFT_TIME_LIMIT = 350000  # Мягкий лимит (97 часов) - увеличен для очень больших файлов
CELERY_WORKER_SEND_TASK_EVENTS = False  # Отключаем события для экономии ресурсов
CELERY_TASK_IGNORE_RESULT = False  # Сохраняем результаты для предотвращения повторного выполнения
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Отклоняем задачи при потере воркера
CELERY_TASK_ALWAYS_EAGER = False  # Не выполняем задачи синхронно
CELERY_TASK_EAGER_PROPAGATES = True  # Пробрасываем исключения при синхронном выполнении
